#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

script_dir_path="$(dirname -- "$0" && printf x)"
script_dir_path="${script_dir_path%"$(printf '\nx')"}"
readonly script_dir_path

keymap_file_path="$script_dir_path/keymap.xml"
readonly keymap_file_path

keymap_name="$(grep -E -- 'name="[^"]+"' "$keymap_file_path" | head -n1 | sed s/'^.*name="\([^"]\{1,\}\)".*$'/'\1'/)"
readonly keymap_name

#region setting up temporary directory

tmp_dir_path="$script_dir_path/_settings"
readonly tmp_dir_path

remove_tmp_dir() {
	rm -rf -- "$tmp_dir_path"
}

trap remove_tmp_dir EXIT
trap 'trap - EXIT; remove_tmp_dir' INT QUIT TERM

mkdir -p -- "$tmp_dir_path"

#endregion

mkdir -p -- "$tmp_dir_path/keymaps"
cp -- "$keymap_file_path" "$tmp_dir_path/keymaps/$keymap_name.xml"

mkdir -p -- "$tmp_dir_path/options/linux"
{
	printf '<application>\n'
	printf '\t<component name="KeymapManager">\n'
	printf '\t\t<active_keymap name="%s" />\n' "$keymap_name"
	printf '\t</component>\n'
	printf '</application>\n'
} > "$tmp_dir_path/options/linux/keymap.xml"

(
	cd -- "$tmp_dir_path"
	zip -r '../settings.zip' .
)
