#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# SPDX-License-Identifier: CC0-1.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

if ! command -v git > '/dev/null'; then
	printf '%s: git: program missing\n' "$argv0" >&2
	exit 1
fi

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %d\n' "$argv0" $# >&2
	exit 2
fi

case "$(git rev-parse --is-bare-repository)" in
	('true') exit ;;
	('false') ;;
	(*)
		# shellcheck disable=SC2016
		printf '%s: unexpected output of `git rev-parse --is-bare-repository`\n' "$argv0" >&2

		exit 1
		;;
esac

tmp="$(git diff --staged --name-only -- 'manager-application/**/*.kt' 'manager-application/**/*.kts' | wc -c)"
if [ "$tmp" = '0' ]; then
	printf 'No Kotlin files staged in the directory "manager-application". Skipping commit hook.\n' >&2
	exit
fi
unset -v tmp

# TODO: Automatically install the correct ktlint version.
if ! command -v ktlint > '/dev/null'; then
	printf '%s: ktlint: program missing\n' "$argv0" >&2
	exit 1
fi

# TODO: This only checks files that are contained in HEAD's tree. Change it so that the index is queried instead.
git ls-tree -r --name-only HEAD |
	grep -E '\.kts?$' |
	ktlint --color --relative --reporter='plain?group_by_file' --patterns-from-stdin='
' --log-level='none'
