#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

#region args

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %i\n' "$argv0" $# >&2
	exit 4
fi

#endregion

#region main

script_dir_pathname="$(dirname -- "$0" && printf x)"
script_dir_pathname="${script_dir_pathname%"$(printf '\nx')"}"
readonly script_dir_pathname

#region setting up temporary repository

tmp_repo_dir_pathname="$script_dir_pathname/_vim_code_dark.git"
readonly tmp_repo_dir_pathname

remove_tmp_repo_dir() {
	rm -rf -- "$tmp_repo_dir_pathname"
}

mkdir -- "$tmp_repo_dir_pathname"

trap remove_tmp_repo_dir EXIT
trap 'trap - EXIT; remove_tmp_repo_dir' INT QUIT TERM

git clone --branch='master' --depth=1 --single-branch --no-tags -- \
	'https://github.com/tomasiser/vim-code-dark.git' "$tmp_repo_dir_pathname"

#endregion

commit_hash="$(git -C "$tmp_repo_dir_pathname" --no-pager show --no-abbrev-commit --pretty=format:'%H' --no-patch HEAD)"
readonly commit_hash

{
	head -n3 -- "$tmp_repo_dir_pathname/colors/codedark.vim"
	printf "\" <https://github.com/tomasiser/vim-code-dark/blob/%s/colors/codedark.vim>\\n" "$commit_hash"
	tail -n+3 -- "$tmp_repo_dir_pathname/colors/codedark.vim"
} > "$script_dir_pathname/colorscheme-codedark.vim"

#endregion
