#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

starts_with() {
	test "${1%"$2"}" != "$1"
}

script_dir_path="$(dirname -- "$0" && printf x)"
script_dir_path="${script_dir_path%"$(printf '\nx')"}"
readonly script_dir_path

manager_application_dir_path="$script_dir_path/manager-application"
if starts_with "$manager_application_dir_path" '-'; then
	# Required for `find`
	manager_application_dir_path="./$manager_application_dir_path"
fi
readonly manager_application_dir_path


manager_application_jar_file_path="$manager_application_dir_path/build/libs/system-setup-manager-all.jar"
readonly manager_application_jar_file_path


needs_build=false

if ! [ -f "$manager_application_jar_file_path" ]; then
	needs_build=true
fi

if ! $needs_build; then
	n=$(find "$manager_application_dir_path" \
	         -not \( \
		         -path "$manager_application_dir_path/.gradle" -o -path "$manager_application_dir_path/.gradle/*" -o \
		         -path "$manager_application_dir_path/.kotlin" -o -path "$manager_application_dir_path/.kotlin/*" -o \
		         -path "$manager_application_dir_path/build" -o -path "$manager_application_dir_path/build/*" \
	         \) \
	         -newer "$manager_application_jar_file_path" -exec printf x \; |
		         wc -c)

	if [ "$n" != 0 ]; then
		needs_build=true
	fi

	unset -v n
fi

if $needs_build; then
	printf 'Manager application needs build...\n\n--------------------------------------------------------------------------------\n' >&2

	(
		cd -- "$manager_application_dir_path"
		./gradlew clean shadowJar >&2
	)

	printf '\n--------------------------------------------------------------------------------\n\n' >&2
fi

java -jar "$manager_application_jar_file_path" "$@"
