#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

script_dir_path="$(dirname -- "$0" && printf x)"
script_dir_path="${script_dir_path%"$(printf '\nx')"}"
readonly script_dir_path

cd -- "$script_dir_path"

find 'setup/bin' \( -name '*.sh' -or -name '*.bash' \) \
                 -not \( \
	                 -path 'setup/bin/atype.bash' -or \
	                 -path 'setup/bin/ktlint-install.sh' -or \
	                 -path 'setup/bin/mkbak.bash' \
                 \) \
                 -exec shellcheck {} +

find 'setup' \( -name '*.sh' -or -name '*.bash' \) \
             -not -path 'setup/bin/*' \
             -not \( \
	             -path 'setup/programs/bash/completions/adb.bash' -or \
	             -path 'setup/programs/bash/completions/gradle.bash' \
             \) \
             -exec shellcheck --external-sources {} +
