#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2024 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %i\n' "$argv0" $# >&2
	exit 4
fi

if ! command -v localectl > '/dev/null'; then
	printf '%s: localectl: program missing\n' "$argv0" >&2
	exit 27
fi

custom_locale_name='en_AT.UTF-8@custom'
readonly custom_locale_name

localectl set-locale "$custom_locale_name"

if command -v gsettings > '/dev/null'; then
	gsettings set 'org.gnome.system.locale' 'region' "$custom_locale_name"
fi
