#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2023 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes


if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0


if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %i\n' "$argv0" $# >&2
	exit 4
fi


root_dir_pathname="$(dirname -- "$0" && printf x)"
root_dir_pathname="${root_dir_pathname%"$(printf '\nx')"}"
readonly root_dir_pathname

#region setting up temporary repository

tmp_repo_dir_pathname="$root_dir_pathname/_adb_completion_tmp.git"
readonly tmp_repo_dir_pathname

remove_tmp_repo_dir() {
	rm -rf -- "$tmp_repo_dir_pathname"
}

mkdir -- "$tmp_repo_dir_pathname"

trap remove_tmp_repo_dir EXIT
trap 'trap - EXIT; remove_tmp_repo_dir' INT QUIT TERM

git clone --sparse --depth=1 --single-branch --no-tags -- 'https://gist.github.com/7677543.git' "$tmp_repo_dir_pathname"

#endregion

commit_hash="$(git -C "$tmp_repo_dir_pathname" --no-pager show --no-abbrev-commit --pretty=format:'%H' --no-patch HEAD)"
readonly commit_hash

#region writing to completion file

{
	head -n17 -- "$tmp_repo_dir_pathname/adb-completion.bash"
	printf '# <https://gist.github.com/otobrglez/7677543/%s>\n' "$commit_hash"
	tail -n+17 -- "$tmp_repo_dir_pathname/adb-completion.bash"
} > "$root_dir_pathname/adb.bash"

#endregion
