# SPDX-License-Identifier: CC0-1.0

[libraries]
kotlinxImmutableCollections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.5.1"

junit-bom = "org.junit:junit-bom:6.1.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlinJvm = "org.jetbrains.kotlin.jvm:2.4.10"
shadow = "com.gradleup.shadow:9.6.1"
