#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %d\n' "$argv0" $# >&2
	exit 4
fi

script_dir_path="$(dirname -- "$0" && printf x)"
script_dir_path="${script_dir_path%"$(printf '\nx')"}"
readonly script_dir_path

cspell_dictionaries_dir_path="$XDG_CONFIG_HOME/VSCodium/User/cSpell-dictionaries"
readonly cspell_dictionaries_dir_path

mkdir -p -- "$cspell_dictionaries_dir_path"

sed s/'^\(.*\)#.*$'/'\1'/ "$script_dir_path/custom-cspell-dictionary.cfg" |
	tr '[:space:]' '\n' |
	grep -Ev '^[[:space:]]*$' |
	sort > "$cspell_dictionaries_dir_path/public.txt"
