#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

# Copyright (c) 2025 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

print_usage() {
	printf 'usage: %s [un]install\n' "$argv0"
}

case $# in
	(0)
		# TODO
		;;
	(1)
		case "$1" in
			('install'|'uninstall') ;;
			(*)
				# TODO
				;;
		esac
		;;
	(*)
		{
			printf '%s: too many arguments: %d\n' "$argv0" $(($# - 1))
			print_usage
		} >&2
		exit 4
		;;
esac

starts_with() {
	test "${1#"$2"}" != "$1"
}

script_dir_path="$(dirname -- "$0" && printf x)"
script_dir_path="${script_dir_path%"$(printf '\nx')"}"
readonly script_dir_path

config_base_dir_path="${XDG_CONFIG_HOME-}"
if ! starts_with "$config_base_dir_path" '/'; then
	if [ -z "${HOME-}" ]; then
		# TODO
		printf ''
		exit 1
	fi

	config_base_dir_path="$HOME/.config"
fi
readonly config_base_dir_path

cspell_dictionaries_dir_path="$config_base_dir_path/VSCodium/User/cSpell-dictionaries"
readonly cspell_dictionaries_dir_path

public_cspell_dictionary_file_path="$cspell_dictionaries_dir_path/public.txt"
readonly public_cspell_dictionary_file_path

case "$1" in
	('install')
		mkdir -p -- "$cspell_dictionaries_dir_path"

		sed s/'^\(.*\)#.*$'/'\1'/ "$script_dir_path/custom-cspell-dictionary.cfg" |
			tr '[:space:]' '\n' |
			grep -Ev '^[[:space:]]*$' |
			sort > "$public_cspell_dictionary_file_path"
		;;
	('uninstall')
		rm -f -- "$public_cspell_dictionary_file_path"

		rmdir -p -- "$cspell_dictionaries_dir_path" > '/dev/null' 2> '/dev/null' || true
		;;
esac
